#ifndef _BaseDef_H
#define _BaseDef_H
 
static char BaseDef_H [] =
"@(#) dbE $Header: http://belov.homenet.org/svn/trunk/base/def/BaseDef.H 247 2013-12-30 07:34:12Z db $";  

/*
  $Log: not supported by cvs2svn $
  Revision 1.9  2000/11/04 15:42:20  db
  errno.h included

  Revision 1.8  2000/11/01 18:18:25  db
  string.h included

  Revision 1.7  2000/10/31 22:25:30  db
  sys/time included

  Revision 1.6  2000/10/25 20:17:12  db
  included unistd.h

  Revision 1.5  2000/10/18 00:35:38  db
  misc. fixes

  Revision 1.4  2000/10/16 21:42:52  db
  stdlib.h included

  Revision 1.3  2000/10/16 21:27:19  db
  ifndef

  Revision 1.2  2000/10/12 21:40:33  db
  typedef Date

  Revision 1.1  2000/10/12 21:25:47  db
  *** empty log message ***

*/ 

//=========== Types ======
//typedef mytype_t Type;

//=========== Macros ======

#endif // _BaseDef_H 
