# $Header: $

SUBDIRS = extproc uobj java
ifndef MAKEFILE
    MAKEFILE = makefile
endif
include ../$(MAKEFILE)

# poss. depedencies, when order is important
#tpl: def obj time exc str
#sock: pth map


